name: Sync LibreLinkUp Glucose

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install glucose dependencies
        run: npm install
        working-directory: glucose-sync

      - name: Run glucose sync
        run: node sync.js
        working-directory: glucose-sync
        env:
          LIBRE_LINK_EMAIL: ${{ secrets.LIBRE_LINK_EMAIL }}
          LIBRE_LINK_PASSWORD: ${{ secrets.LIBRE_LINK_PASSWORD }}
          LIBRE_LINK_UP_VERSION: ${{ secrets.LIBRE_LINK_UP_VERSION }}
          LIBRE_LINK_API_URL: ${{ secrets.LIBRE_LINK_API_URL }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}